# Generated by Django 2.2.6 on 2019-11-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20191102_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
