# Generated by Django 2.2.6 on 2019-11-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_place_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Type',
            new_name='WhatTypes',
        ),
    ]
