# Generated by Django 2.2.8 on 2019-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191102_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Rating',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
